name: Build and Publish Docker images

on:
  push:
    tags:
      - v*
  # Allow manual triggers
  workflow_dispatch:

env:
  # Change this to your Docker Hub username
  DOCKER_HUB_USERNAME: heispv
  # Change this to your Docker repository name
  DOCKER_REPOSITORY: pymmseqs

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_REPOSITORY }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha

      # Build and push Debian-based image
      - name: Build and push Debian image
        uses: docker/build-push-action@v4
        with:
          context: .
          target: debian-build
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:debian
          labels: ${{ steps.meta.outputs.labels }}

      # Build and push Alpine-based image
      - name: Build and push Alpine image
        uses: docker/build-push-action@v4
        with:
          context: .
          target: alpine-build
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:alpine
          labels: ${{ steps.meta.outputs.labels }}