name: Build and Publish Docker Images

on:
  workflow_dispatch:

env:
  DOCKER_HUB_USERNAME: heispv
  DOCKER_REPOSITORY: pymmseqs

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Debian-based image with 'latest' tag
      - name: Build and push Debian image
        uses: docker/build-push-action@v4
        with:
          context: .
          target: debian-build
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:debian
            ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:latest

      # Build and push Alpine-based image
      - name: Build and push Alpine image
        uses: docker/build-push-action@v4
        with:
          context: .
          target: alpine-build
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.DOCKER_REPOSITORY }}:alpine
