# .github/workflows/test_publish.yaml

name: Test and Publish to PyPI

on:
  push:
    branches: [master]
    tags:
      - v*
  pull_request:
    branches: [master]
  
env:
  CIBW_BUILD_VERBOSITY: 1

jobs:
  # test:
  #   strategy:
  #     matrix:
  #       os: [macos-latest] #ubuntu-latest, macos-13, 
  #       python-version: ["3.10"] # 3.11
  #   runs-on: ${{ matrix.os }}

  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Set up Python
  #       uses: actions/setup-python@v4
  #       with:
  #         python-version: ${{ matrix.python-version }}

  #     - name: Install MMseqs2 (Ubuntu)
  #       if: matrix.os == 'ubuntu-latest'
  #       run: |
  #         sudo apt-get update
  #         sudo apt-get install -y mmseqs2
      
  #     - name: Install MMseqs2 (macOS)
  #       if: startsWith(matrix.os, 'macos')
  #       run: |
  #         brew install mmseqs2
      
  #     - name: Install dependencies
  #       run: |
  #         python -m pip install --upgrade pip
  #         pip install pytest
  #         pip install .

  #     - name: Run with pytest
  #       run: |
  #         pytest tests/

  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest] #ubuntu-22.04, macos-14
        python-version: ["3.10"] #, "3.12", "3.13"
    
    steps:
      - name : Checkout out code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Install cibuildwheel
        run: pip install cibuildwheel==2.22.0
      
      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-py${{ matrix.python-version }}
          path: dist/*.whl

  # build_sdist:
  #   needs: build_wheels
  #   name: Build sdist
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Build sdist
  #       run: |
  #         pipx run build --sdist

  #     - name: Upload sdist
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: cibw-sdist
  #         path: dist/*.tar.gz

  # publish_pypi:
  #   needs: [build_wheels, build_sdist]
  #   runs-on: ubuntu-latest
  #   environment: pymmseqs-testpypi
  #   permissions:
  #     id-token: write
  #   if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
  #   steps:
  #     - uses: actions/download-artifact@v4
  #       with:
  #         pattern: cibw-*
  #         path: dist
  #         merge-multiple: true

  #     - uses: pypa/gh-action-pypi-publish@release/v1
  #       with:
  #         repository-url: https://test.pypi.org/legacy/
